site_name: 'Ardublockly Documentation'
site_url: http://ardublockly.embeddedlog.com
repo_url: http://github.com/carlosperate/ardublockly/wiki
site_description: Visual programming for Arduino.
site_author: carlosperate
site_dir: ../../docs
docs_dir: 'ardublockly.wiki'
theme: 'readthedocs'

# It is IMPERATIVE to leave this property to the end without anything after it.
# This is because the build file will delete everything after this line and
# replace it with newly generated data.
pages:
- Home: 'Home.md'
- Quick Start: 'Quick-Start.md'
- User Guide:
    - Installing Ardublockly: 'Installing-Ardublockly.md'
    - Configure Ardublockly: 'Configure-Ardublockly.md'
    - Arduino Compiler Settings: 'Arduino-Compiler-Settings.md'
    - General Blocks:
        - Logic: 'Create-~-Logic.md'
        - Logic If/Else: 'Create-~-IfElse.md'
        - Loops: 'Create-~-Loops.md'
        - Math: 'Create-~-Math.md'
        - Text: 'Create-~-Text.md'
        - Variables: 'Create-~-Variables.md'
        - Functions: 'Create-~-Functions.md'
- FAQs: 'FAQs.md'
- Known Arduino IDE issues: 'Known-Arduino-IDE-issues.md'
- Developer Guide:
    - Building Ardublockly: 'Building-Ardublockly.md'
    - Running Uncompressed Ardublockly: 'Running-Uncompressed-Ardublockly.md'
    - Git Settings: 'Git-Settings.md'
    - Create Blocks:
        - Overview: 'Create-Blocks.md'
        - Extending Ardublockly: 'Create-Blocks-~-Extending-Ardublockly.md'
    - Add a New Board: 'Add-New-Arduino-Board.md'
    - Add a New Language: 'Add-New-Language.md'
    - To-do List: 'To-do-list.md'
- About:
    - About Ardublockly: 'About.md'
    - License: 'License.md'
    - Credits: 'Credits.md'
